---

kind: pipeline
type: docker
name: lint

steps:
  - name: lint
    image: python:3-alpine
    commands:
      - apk add --no-cache make
      - pip install -r requirements.style.txt
      - make lint

---

kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: python:3.9-alpine
    commands:
      - apk add --no-cache make
      - pip install -r tests/unit/plugins/requirements.txt
      - make test

---

kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: python:alpine
    commands:
      - apk add --no-cache make
      - pip install ansible
      - make build

  # TODO: publish step
