---

namespace: colin_nolan
name: rpi
version: 1.0.0
readme: README.md
authors:
  - Colin Nolan <cn580@alumni.york.ac.uk>
description: collection of Raspberry Pi related modules
license:
  - MIT
repository: https://github.com/colin-nolan/ansible-collection-rpi
documentation: https://github.com/colin-nolan/ansible-collection-rpi/blob/main/README.md
homepage: https://github.com/colin-nolan/ansible-collection-rpi
issues: https://github.com/colin-nolan/ansible-collection-rpi/issues
build_ignore:
  - collections
  - build