---

namespace: colin_nolan
name: boot_cmdline
version: 1.0.0
readme: README.md
authors:
  - Colin Nolan <cn580@alumni.york.ac.uk>
# TODO
description: your collection description
license:
  - MIT
# TODO
tags: []
dependencies: {}
repository: https://github.com/colin-nolan/ansible-module-boot-cmdline
documentation: https://github.com/colin-nolan/ansible-module-boot-cmdline/blob/main/README.md
homepage: https://github.com/colin-nolan/ansible-module-boot-cmdline
issues: https://github.com/colin-nolan/ansible-module-boot-cmdline/issues
build_ignore: []
